# Generated by Django 3.0.6 on 2020-07-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('product_id', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('Kid', 'Kid'), ('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('dissprice', models.IntegerField()),
                ('cart_image', models.ImageField(blank=True, upload_to='')),
                ('quantity', models.IntegerField(default=1)),
                ('amount', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='dyn_slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dyn_img1', models.ImageField(blank=True, upload_to='dynamic_images/')),
                ('dyn_img2', models.ImageField(blank=True, upload_to='dynamic_images/')),
                ('dyn_img3', models.ImageField(blank=True, upload_to='dynamic_images/')),
                ('dysp', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='order_DB',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=1000)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=1000)),
                ('size', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=20)),
                ('payment_type', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('state_zip', models.CharField(max_length=1000)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('ordered', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('processing', models.BooleanField(default=True)),
                ('order_status', models.CharField(max_length=1000)),
                ('delivery_date', models.CharField(blank=True, max_length=100)),
                ('order_image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='product_DB',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('Kid', 'Kid'), ('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('dissprice', models.IntegerField()),
                ('description', models.TextField()),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='M', max_length=20)),
                ('new', models.BooleanField(default=False)),
                ('bestseller', models.BooleanField(default=False)),
                ('outofstock', models.BooleanField(default=False)),
                ('fewleft', models.BooleanField(default=False)),
                ('front_image', models.ImageField(blank=True, upload_to='prodimages/')),
                ('back_image', models.ImageField(blank=True, upload_to='prodimages/')),
                ('model_image', models.ImageField(blank=True, upload_to='prodimages/')),
            ],
        ),
        migrations.CreateModel(
            name='promocode_available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='promocode_used',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_txt', models.CharField(max_length=30)),
                ('date_used', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
