# Generated by Django 3.0.6 on 2020-06-01 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='product_DB',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('dissprice', models.IntegerField()),
                ('description', models.TextField()),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='M', max_length=20)),
                ('new', models.BooleanField(default=False)),
                ('bestseller', models.BooleanField(default=False)),
                ('outofstock', models.BooleanField(default=False)),
                ('fewleft', models.BooleanField(default=False)),
                ('front_image', models.ImageField(blank=True, upload_to='store/prodimages')),
                ('back_image', models.ImageField(blank=True, upload_to='store/prodimages')),
                ('model_image', models.ImageField(blank=True, upload_to='store/prodimages')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category_DB')),
            ],
        ),
    ]
