# Generated by Django 3.0.6 on 2020-06-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_db',
            name='category',
            field=models.CharField(choices=[('Kid', 'Kid'), ('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
        migrations.DeleteModel(
            name='category_DB',
        ),
    ]
