# Generated by Django 3.0.6 on 2020-07-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_db',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='order_db',
            name='city',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_db',
            name='lastname',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_db',
            name='state',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
