# Generated by Django 3.0.6 on 2020-07-19 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200716_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_db',
            name='cart_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_db',
            name='color',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_db',
            name='price',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
