# Generated by Django 3.0.6 on 2020-06-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200601_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_db',
            name='back_image',
            field=models.ImageField(blank=True, upload_to='prodimages/'),
        ),
        migrations.AlterField(
            model_name='product_db',
            name='front_image',
            field=models.ImageField(blank=True, upload_to='prodimages/'),
        ),
        migrations.AlterField(
            model_name='product_db',
            name='model_image',
            field=models.ImageField(blank=True, upload_to='prodimages/'),
        ),
    ]
