# Generated by Django 3.0.6 on 2020-06-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200601_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('product_id', models.CharField(max_length=100)),
            ],
        ),
    ]
