# Generated by Django 3.0.6 on 2020-06-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_DB',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=1000)),
                ('size', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=20)),
                ('payment_type', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cart_db',
            name='cart_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cart_db',
            name='category',
            field=models.CharField(choices=[('Kid', 'Kid'), ('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart_db',
            name='dissprice',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart_db',
            name='price',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
