# Generated by Django 3.0.6 on 2020-06-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200604_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_db',
            name='username',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
