# Generated by Django 3.0.6 on 2020-06-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_db_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_db',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
