# Generated by Django 3.0.6 on 2020-06-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20200604_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_db',
            name='order_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
