# Generated by Django 3.0.6 on 2020-06-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_db_order_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_db',
            name='product_name',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
