# Generated by Django 3.0.6 on 2020-06-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_db_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='dyn_slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dyn_img1', models.ImageField(blank=True, upload_to='dynamic_images/')),
                ('dyn_img2', models.ImageField(blank=True, upload_to='dynamic_images/')),
                ('dyn_img3', models.ImageField(blank=True, upload_to='dynamic_images/')),
                ('dysp', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
    ]
