# Generated by Django 3.0.6 on 2020-06-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_dyn_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='promocode_available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='promocode_used',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_txt', models.CharField(max_length=30)),
                ('date_used', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
